fixup! push to a test branch to validate token permissions

diff --git a/.github/workflows/health-api-library.publish.docs.yml b/.github/workflows/health-api-library.publish.docs.yml
--- a/.github/workflows/health-api-library.publish.docs.yml
+++ b/.github/workflows/health-api-library.publish.docs.yml
@@ -52,12 +52,32 @@ jobs:
         app-id: ${{ secrets.MOBILE_CI_APP_ID }}
         private-key: ${{ secrets.MOBILE_CI_APP_PRIVATE_KEY }}
         owner: gini
-    - name: Use the token
+
+      # useful references in the README on: https://github.com/actions/create-github-app-token 
+      - name: Get GitHub App User ID
+        id: get-user-id
+        run: echo "user-id=$(gh api "/users/${{ steps.generate-token.outputs.app-slug }}[bot]" --jq .id)" >> "$GITHUB_OUTPUT"
+        env:
+          GH_TOKEN: ${{ steps.generate-token.outputs.token }}
+
+    # (feel free to remove this comment before merging, just a note)
+    # @Nadya this can probably work by passing in `x-oauth-token` as username to fastlane and GH_TOKEN as pass.
+    # Otherwise, this handling will give it a clean-ish git conf.
+    - name: Configure the git client
       env:
         GH_TOKEN: ${{ steps.generate-token.outputs.token }}
       run: |
-        gh auth setup-git
-        git push origin HEAD:daniel-testing-stuff
+        echo git config --local user.name '${{ steps.generate-token.outputs.app-slug }}[bot]'
+        echo git config --local user.email '${{ steps.get-user-id.outputs.user-id }}+${{ steps.generate-token.outputs.app-slug }}[bot]@users.noreply.github.com'
+        git config --local user.name '${{ steps.generate-token.outputs.app-slug }}[bot]'
+        git config --local user.email '${{ steps.get-user-id.outputs.user-id }}+${{ steps.generate-token.outputs.app-slug }}[bot]@users.noreply.github.com'
+        # We must ditch all the cred details the checkout action fills in
+        # otherwise this conflicts with our basic auth passed in the remote and fails to push
+        git config --local credential.helper ""
+        git config --local --unset http.https://github.com/.extraheader || true
+        git remote remove origin || true
+        git remote add origin https://x-oauth-token:${GH_TOKEN}@github.com/gini/gini-mobile-ios.git
+        git push origin HEAD:daniel-test-happy-days
 
     - name: Publish GiniHealthAPILibrary documentation to the release repo
       uses: maierj/fastlane-action@5a3b971aaa26776459bb26894d6c1a1a84a311a7 # v3.1.0
